### ISSUE TITLE
cisco_ios_show_power_inline.textfsm for older switches

### ISSUE THREAD

**Issue by Mikeg2881** [networktocode/ntc-templates#2086]
It looks like older switches do not work with `cisco_ios_show_power_inline`.

It looks like Cisco changed how the command looks.

### See script below:
- `poe_output_1` - Fails
- `poe_output_2` - Works  
- `poe_output_3` - Fails  

Both `poe_output_1` and `poe_output_3` are from older IOS/switches.

```python
from ntc_templates.parse import parse_output

platform="cisco_ios"

poe_output_1 = """"
Available:124.0(w)  Used:61.6(w)  Remaining:62.4(w)

Interface Admin  Oper       Power   Device              Class Max
                            (Watts)                            
--------- ------ ---------- ------- ------------------- ----- ----
Fa0/1     auto   on         15.4    Ieee PD             3     15.4 
Fa0/2     auto   on         15.4    Ieee PD             3     15.4 
Fa0/3     auto   on         15.4    CW9162I-MR          4     15.4 
Fa0/4     auto   off        0.0     n/a                 n/a   15.4 
Fa0/5     auto   off        0.0     n/a                 n/a   15.4 
Fa0/6     auto   off        0.0     n/a                 n/a   15.4 
Fa0/7     auto   off        0.0     n/a                 n/a   15.4 
Fa0/8     auto   off        0.0     n/a                 n/a   15.4 
Fa0/9     auto   off        0.0     n/a                 n/a   15.4 
Fa0/10    auto   off        0.0     n/a                 n/a   15.4 
Fa0/11    auto   off        0.0     n/a                 n/a   15.4 
Fa0/12    auto   on         15.4    Ieee PD             4     15.4 

"""

poe_output_2 = """
Module   Available     Used     Remaining
          (Watts)     (Watts)    (Watts)
------   ---------   --------   ---------
1           775.0      123.2       651.8
Interface Admin  Oper       Power   Device              Class Max
                            (Watts)
--------- ------ ---------- ------- ------------------- ----- ----
Gi1/0/1   auto   off        0.0     n/a                 n/a   30.0
Gi1/0/2   auto   off        0.0     n/a                 n/a   30.0
Gi1/0/3   auto   off        0.0     n/a                 n/a   30.0
Gi1/0/4   auto   off        0.0     n/a                 n/a   30.0
Gi1/0/5   auto   on         15.4    Ieee PD             0     30.0
Gi1/0/6   auto   on         15.4    Ieee PD             0     30.0
Gi1/0/7   auto   off        0.0     n/a                 n/a   30.0
Gi1/0/8   auto   off        0.0     n/a                 n/a   30.0
Gi1/0/9   auto   off        0.0     n/a                 n/a   30.0
Gi1/0/10  auto   on         15.4    Ieee PD             0     30.0
Gi1/0/11  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/12  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/13  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/14  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/15  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/16  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/17  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/18  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/19  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/20  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/21  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/22  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/23  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/24  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/25  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/26  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/27  auto   on         15.4    Ieee PD             0     30.0
Gi1/0/28  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/29  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/30  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/31  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/32  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/33  auto   on         15.4    Ieee PD             0     30.0
Gi1/0/34  auto   on         15.4    Ieee PD             4     30.0
Gi1/0/35  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/36  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/37  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/38  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/39  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/40  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/41  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/42  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/43  auto   on         15.4    Ieee PD             4     30.0
Gi1/0/44  auto   on         15.4    Ieee PD             4     30.0
Gi1/0/45  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/46  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/47  auto   off        0.0     n/a                 n/a   30.0
Gi1/0/48  auto   off        0.0     n/a                 n/a   30.0
"""


poe_output_3 = """
Available:6200(w)  Used:443(w)  Remaining:5757(w)

Interface Admin  Oper            Power(Watts)     Device              Class
                            From PS    To Device                    
--------- ------ ---------- ---------- ---------- ------------------- -----

Gi2/1     auto   off        0.0        0.0        n/a                 n/a  
Gi2/2     auto   off        0.0        0.0        n/a                 n/a  
Gi2/3     auto   off        0.0        0.0        n/a                 n/a  
Gi2/4     auto   off        0.0        0.0        n/a                 n/a  
Gi2/5     auto   on         16.2       15.4       Ieee PD             4    
Gi2/6     auto   off        0.0        0.0        n/a                 n/a  
Gi2/7     auto   off        0.0        0.0        n/a                 n/a  
Gi2/8     auto   off        0.0        0.0        n/a                 n/a  
Gi2/9     auto   off        0.0        0.0        n/a                 n/a  
Gi2/10    auto   off        0.0        0.0        n/a                 n/a  
Gi2/11    auto   off        0.0        0.0        n/a                 n/a  
Gi2/12    auto   off        0.0        0.0        n/a                 n/a  
Gi2/13    auto   off        0.0        0.0        n/a                 n/a  
Gi2/14    auto   off        0.0        0.0        n/a                 n/a  
Gi2/15    auto   off        0.0        0.0        n/a                 n/a  
Gi2/16    auto   off        0.0        0.0        n/a                 n/a  
Gi2/17    auto   off        0.0        0.0        n/a                 n/a  
Gi2/18    auto   off        0.0        0.0        n/a                 n/a  
Gi2/19    auto   off        0.0        0.0        n/a                 n/a  
Gi2/20    auto   off        0.0        0.0        n/a                 n/a  
Gi2/21    auto   off        0.0        0.0        n/a                 n/a  
Gi2/22    auto   on         16.2       15.4       Ieee PD             4    
Gi2/23    auto   off        0.0        0.0        n/a                 n/a  
Gi2/24    auto   off        0.0        0.0        n/a                 n/a  
Gi2/25    auto   off        0.0        0.0        n/a                 n/a  
Gi2/26    auto   off        0.0        0.0        n/a                 n/a  
Gi2/27    auto   off        0.0        0.0        n/a                 n/a  
Gi2/28    auto   off        0.0        0.0        n/a                 n/a  
Gi2/29    auto   off        0.0        0.0        n/a                 n/a  
Gi2/30    auto   off        0.0        0.0        n/a                 n/a  
Gi2/31    auto   off        0.0        0.0        n/a                 n/a  
Gi2/32    auto   on         16.2       15.4       Ieee PD             4    
Gi2/33    auto   off        0.0        0.0        n/a                 n/a  
Gi2/34    auto   off        0.0        0.0        n/a                 n/a  
Gi2/35    auto   off        0.0        0.0        n/a                 n/a  
Gi2/36    auto   off        0.0        0.0        n/a                 n/a  
Gi2/37    auto   off        0.0        0.0        n/a                 n/a  
Gi2/38    auto   off        0.0        0.0        n/a                 n/a  
Gi2/39    auto   off        0.0        0.0        n/a                 n/a  
Gi2/40    auto   on         16.2       15.4       Ieee PD             4    
Gi2/41    auto   off        0.0        0.0        n/a                 n/a  
Gi2/42    auto   off        0.0        0.0        n/a                 n/a  
Gi2/43    auto   off        0.0        0.0        n/a                 n/a  
Gi2/44    auto   off        0.0        0.0        n/a                 n/a  
Gi2/45    auto   off        0.0        0.0        n/a                 n/a  
Gi2/46    auto   off        0.0        0.0        n/a                 n/a  
Gi2/47    auto   off        0.0        0.0        n/a                 n/a  
Gi2/48    auto   off        0.0        0.0        n/a                 n/a  
Gi3/1     auto   off        0.0        0.0        n/a                 n/a  
Gi3/2     auto   off        0.0        0.0        n/a                 n/a  
Gi3/3     auto   off        0.0        0.0        n/a                 n/a  
Gi3/4     auto   off        0.0        0.0        n/a                 n/a  
Gi3/5     auto   off        0.0        0.0        n/a                 n/a  
Gi3/6     auto   off        0.0        0.0        n/a                 n/a  
Gi3/7     auto   off        0.0        0.0        n/a                 n/a  
Gi3/8     auto   off        0.0        0.0        n/a                 n/a  
Gi3/9     auto   off        0.0        0.0        n/a                 n/a  
Gi3/10    auto   off        0.0        0.0        n/a                 n/a  
Gi3/11    auto   off        0.0        0.0        n/a                 n/a  
Gi3/12    auto   off        0.0        0.0        n/a                 n/a  
Gi3/13    auto   off        0.0        0.0        n/a                 n/a  
Gi3/14    auto   off        0.0        0.0        n/a                 n/a  
Gi3/15    auto   off        0.0        0.0        n/a                 n/a  
Gi3/16    auto   off        0.0        0.0        n/a                 n/a  
Gi3/17    auto   off        0.0        0.0        n/a                 n/a  
Gi3/18    auto   off        0.0        0.0        n/a                 n/a  
Gi3/19    auto   off        0.0        0.0        n/a                 n/a  
Gi3/20    auto   off        0.0        0.0        n/a                 n/a  
Gi3/21    auto   off        0.0        0.0        n/a                 n/a  
Gi3/22    auto   off        0.0        0.0        n/a                 n/a  
Gi3/23    auto   off        0.0        0.0        n/a                 n/a  
Gi3/24    auto   off        0.0        0.0        n/a                 n/a  
Gi3/25    auto   on         31.6       30.0       C9120AXI-A          4    
Gi3/26    auto   off        0.0        0.0        n/a                 n/a  
Gi3/27    auto   on         31.6       30.0       C9120AXI-A          4    
Gi3/28    auto   off        0.0        0.0        n/a                 n/a  
Gi3/29    auto   on         31.6       30.0       C9120AXI-A          4    
Gi3/30    auto   off        0.0        0.0        n/a                 n/a  
Gi3/31    auto   on         31.6       30.0       C9120AXI-A          4    
Gi3/32    auto   off        0.0        0.0        n/a                 n/a  
Gi3/33    auto   on         31.6       30.0       C9120AXI-A          4    
Gi3/34    auto   off        0.0        0.0        n/a                 n/a  
Gi3/35    auto   on         31.6       30.0       C9120AXI-A          4    
Gi3/36    auto   off        0.0        0.0        n/a                 n/a  
Gi3/37    auto   on         31.6       30.0       C9120AXI-A          4    
Gi3/38    auto   off        0.0        0.0        n/a                 n/a  
Gi3/39    auto   on         31.6       30.0       C9120AXI-A          4    
Gi3/40    auto   off        0.0        0.0        n/a                 n/a  
Gi3/41    auto   on         31.6       30.0       C9120AXI-A          4    
Gi3/42    auto   off        0.0        0.0        n/a                 n/a  
Gi3/43    auto   on         31.6       30.0       C9120AXI-A          4    
Gi3/44    auto   off        0.0        0.0        n/a                 n/a  
Gi3/45    auto   on         31.6       30.0       C9120AXI-A          4    
Gi3/46    auto   off        0.0        0.0        n/a                 n/a  
Gi3/47    auto   on         31.6       30.0       C9120AXI-A          4    
Gi3/48    auto   off        0.0        0.0        n/a                 n/a  
Gi9/1     auto   off        0.0        0.0        n/a                 n/a  
Gi9/2     auto   off        0.0        0.0        n/a                 n/a  
Gi9/3     auto   off        0.0        0.0        n/a                 n/a  
Gi9/4     auto   off        0.0        0.0        n/a                 n/a  
Gi9/5     auto   off        0.0        0.0        n/a                 n/a  
Gi9/6     auto   off        0.0        0.0        n/a                 n/a  
Gi9/7     auto   off        0.0        0.0        n/a                 n/a  
Gi9/8     auto   off        0.0        0.0        n/a                 n/a  
Gi9/9     auto   off        0.0        0.0        n/a                 n/a  
Gi9/10    auto   off        0.0        0.0        n/a                 n/a  
Gi9/11    auto   off        0.0        0.0        n/a                 n/a  
Gi9/12    auto   off        0.0        0.0        n/a                 n/a  
Gi9/13    auto   off        0.0        0.0        n/a                 n/a  
Gi9/14    auto   off        0.0        0.0        n/a                 n/a  
Gi9/15    auto   off        0.0        0.0        n/a                 n/a  
Gi9/16    auto   off        0.0        0.0        n/a                 n/a  
Gi9/17    auto   off        0.0        0.0        n/a                 n/a  
Gi9/18    auto   off        0.0        0.0        n/a                 n/a  
Gi9/19    auto   off        0.0        0.0        n/a                 n/a  
Gi9/20    auto   off        0.0        0.0        n/a                 n/a  
Gi9/21    auto   off        0.0        0.0        n/a                 n/a  
Gi9/22    auto   off        0.0        0.0        n/a                 n/a  
Gi9/23    auto   off        0.0        0.0        n/a                 n/a  
Gi9/24    auto   off        0.0        0.0        n/a                 n/a  
Gi9/25    auto   off        0.0        0.0        n/a                 n/a  
Gi9/26    auto   off        0.0        0.0        n/a                 n/a  
Gi9/27    auto   off        0.0        0.0        n/a                 n/a  
Gi9/28    auto   off        0.0        0.0        n/a                 n/a  
Gi9/29    auto   off        0.0        0.0        n/a                 n/a  
Gi9/30    auto   off        0.0        0.0        n/a                 n/a  
Gi9/31    auto   off        0.0        0.0        n/a                 n/a  
Gi9/32    auto   off        0.0        0.0        n/a                 n/a  
Gi9/33    auto   off        0.0        0.0        n/a                 n/a  
Gi9/34    auto   off        0.0        0.0        n/a                 n/a  
Gi9/35    auto   off        0.0        0.0        n/a                 n/a  
Gi9/36    auto   off        0.0        0.0        n/a                 n/a  
Gi9/37    auto   off        0.0        0.0        n/a                 n/a  
Gi9/38    auto   off        0.0        0.0        n/a                 n/a  
Gi9/39    auto   off        0.0        0.0        n/a                 n/a  
Gi9/40    auto   off        0.0        0.0        n/a                 n/a  
Gi9/41    auto   off        0.0        0.0        n/a                 n/a  
Gi9/42    auto   off        0.0        0.0        n/a                 n/a  
Gi9/43    auto   off        0.0        0.0        n/a                 n/a  
Gi9/44    auto   off        0.0        0.0        n/a                 n/a  
Gi9/45    auto   off        0.0        0.0        n/a                 n/a  
Gi9/46    auto   off        0.0        0.0        n/a                 n/a  
Gi9/47    auto   off        0.0        0.0        n/a                 n/a  
Gi9/48    auto   off        0.0        0.0        n/a                 n/a  
--------- ------ ---------- ---------- ---------- ------------------- -----

Totals:          16   on    443.8      421.6     

"""

try:
    print("")
    show_power_inline_parsed = parse_output(platform=platform, command="show power inline", data=poe_output_3)
except Exception as e:
    print(f"Error occurred: {e}")

print("===========================") 
print(show_power_inline_parsed)
print("===========================")

```

CLI Failure
```

Error occurred: State Error raised. Rule Line: 16. Input Line: Available:6200(w)  Used:443(w)  Remaining:5757(w)
-------------------------
Traceback (most recent call last):
  File "C:\Users\mgrous\OneDrive - Presidio Networked Solutions, Inc\Mikes Drive\Code\Network Visio (Pyvis) - Tests\Test Scripts\ntc_cisco_ios_show_power_inline\ntc_cisco_ios_show_power_inline.py", line 249, in <module>
    print(show_power_inline_parsed)
NameError: name 'show_power_inline_parsed' is not defined
```

**Comment by mjbear** [comment]
@Mikeg2881 
1. Would you please share which version of IOS/IOS-XE each of those outputs came from?

1. Are you interested in working up template changes to submit a pull request (PR)?

**Comment by mjbear** [comment]
> 1.) poe_output_2 WS-C3650-48FQM - flash:/cat3k_caa-universalk9.16.03.08.SPA.bin"
> 
> poe_output_3 4510 with sup 7 - 03.02.00.SG
> 
> poe_output_1 WS-C3560-12PC-S - flash:/c3560-ipbase-mz.122-46.SE/c3560-ipbase-mz.122-46.SE.bin
> 
> (CAT9K_IOSXE), Version 17.3.3 displays just like output_2

I suppose that's good the output didn't change from 16.x to 17.x :grinning:

Thank you for the details.

> 2.) I have tried editing these textfsm files but didnt have much luck with it as i dont really know the syntax on how to do it.

Understood.
I'll take a peek.

**Comment by mjbear** [comment]
`poe_output_1` - we have test data for ios12 so that should parse fine. Please check what version of ntc-templates you have or if you cloned the repo, please pull down changes.

`poe_output_2` - was already working, so good there.

`poe_output_3` - yeah, this one needs some tweaks to support the 45xx PoE output

As it turns out for the third output (45xx), the logic for other versions regarding blank lines caused issues. So I ended up setting up a whole new State to transition to.

Should be fixed by PR #2089

**Comment by Mikeg2881** [comment]
I still show this as not working for poe_output_1

Error occurred: State Error raised. Rule Line: 18. Input Line: "

**Comment by mjbear** [comment]
> I still show this as not working for poe_output_1
> 
> Error occurred: State Error raised. Rule Line: 18. Input Line: "

I tested the `poe_output_1` string as I did last night and it parses without error.

Is there something with the output that I'm missing?

```

Available:124.0(w)  Used:61.6(w)  Remaining:62.4(w)

Interface Admin  Oper       Power   Device              Class Max
                            (Watts)                            
--------- ------ ---------- ------- ------------------- ----- ----
Fa0/1     auto   on         15.4    Ieee PD             3     15.4 
Fa0/2     auto   on         15.4    Ieee PD             3     15.4 
Fa0/3     auto   on         15.4    CW9162I-MR          4     15.4 
Fa0/4     auto   off        0.0     n/a                 n/a   15.4 
Fa0/5     auto   off        0.0     n/a                 n/a   15.4 
Fa0/6     auto   off        0.0     n/a                 n/a   15.4 
Fa0/7     auto   off        0.0     n/a                 n/a   15.4 
Fa0/8     auto   off        0.0     n/a                 n/a   15.4 
Fa0/9     auto   off        0.0     n/a                 n/a   15.4 
Fa0/10    auto   off        0.0     n/a                 n/a   15.4 
Fa0/11    auto   off        0.0     n/a                 n/a   15.4 
Fa0/12    auto   on         15.4    Ieee PD             4     15.4 

```

results in

```yaml
---                                                                                                                                                                                             19:11:36 [16/1860]
parsed_sample:               
  - admin_status: "auto"
    class: "3"          
    device: "Ieee PD"
    interface: "Fa0/1"
    max: "15.4"        
    operational_status: "on"
    power: "15.4"            
  - admin_status: "auto"
    class: "3"          
    device: "Ieee PD"
    interface: "Fa0/2"
    max: "15.4"        
    operational_status: "on"
    power: "15.4"           
  - admin_status: "auto"
    class: "4"                                                                                           
    device: "CW9162I-MR"
    interface: "Fa0/3"
    max: "15.4"
    operational_status: "on"
    power: "15.4"
  - admin_status: "auto"
    class: "n/a"
    device: "n/a"
    interface: "Fa0/4"
    max: "15.4"
    operational_status: "off"
    power: "0.0"
  - admin_status: "auto"
    class: "n/a"
    device: "n/a"
    interface: "Fa0/5"
    max: "15.4"
    operational_status: "off"
    power: "0.0"
  - admin_status: "auto"
    class: "n/a"
    device: "n/a"
    interface: "Fa0/6"
    max: "15.4"
    operational_status: "off"
    power: "0.0"
  - admin_status: "auto"
    class: "n/a"
    device: "n/a"
    interface: "Fa0/7"
    max: "15.4"
    operational_status: "off"
    power: "0.0"
  - admin_status: "auto"
    class: "n/a"
    device: "n/a"
    interface: "Fa0/8"
    max: "15.4"
    operational_status: "off"
    power: "0.0"
  - admin_status: "auto"
    class: "n/a"
    device: "n/a"
    interface: "Fa0/9"
    max: "15.4"
    operational_status: "off"
    power: "0.0"
  - admin_status: "auto"
    class: "n/a"
    device: "n/a"
    interface: "Fa0/10"
    max: "15.4"
    operational_status: "off"
    power: "0.0"
  - admin_status: "auto"
    class: "n/a"
    device: "n/a"
    interface: "Fa0/11"
    max: "15.4"
    operational_status: "off"
    power: "0.0"
  - admin_status: "auto"
    class: "4"
    device: "Ieee PD"
    interface: "Fa0/12"
    max: "15.4"
    operational_status: "on"
    power: "15.4"
```

**Comment by Mikeg2881** [comment]
Apologies I must have typoed/fat fingered something it works now.  As does 2 and 3.

**Comment by mjbear** [comment]
> Apologies I must have typoed/fat fingered something it works now. As does 2 and 3.

Great news!
Thank you @Mikeg2881 for testing!
